name: web EE Tests
on:
  workflow_dispatch:
    jobs:
      - web-tests:
           runs-on: ubuntu-latest
           steps:
             # Clone projeto para a maquina
             - uses: actions/checkout@v4

             # Conferir a versão instalada
             - name: Node.js Version
               run: node --version

             - name: Install Dependencies
               run: npm install

             - name: Executando testes
               run: npx cypress run --spec "cypress/e2e/automation-exercise-modules.cy.js"

             - uses: actions/upload-artifact@v4
               if: ${{ !cancelled() }}
               with:
                 name: relatorios
                 path:
                    - cypress/reports
                    - cypress/screenshots
                    - cypress/videos
