name: web EE Tests
on:
  workflow_dispatch:

jobs:
  web-tests:
    runs-on: ubuntu-latest

    steps:
      # clone do projeto para a máquina
      - uses: actions/checkout@v4

      - name: configurando nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: instalando dependencias
        run: npm install

      - name: executando os testes
        run: npx cypress run --spec "cypress/e2e/automation-exercise-modules*

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorios
          path: |
            cypress/reports
            cypress/screenshots
            cypress/videos
